rohithsprabhu/hacktoberfest2022

c++/Permutations.cpp
created a new branch and added a c++ file
=> added permutations to c++

c/movie_ticket.c
Hey There!
I added the simple movie ticket system using C language.
=> Adding movie_ticket system

c/marksheet_generator.c
I added the new file which simply generates marksheet using C language.
=> Created marsheet generator

c/decitobinary.c
=> Added decimal to binary converter in C

c++/bucketSortAlgos.cpp
Kindly accept this PR and add hacktoberfest accepted tag.
=> added bucket sort algorithm

c++/Infix_To_Postfix.cpp
Hey! I added Infix to Postfix convertor using Stack in CPP. Please mark this as hacktoberfest approved. Thanks !
=> Added Infix to Postfix Convertor using Stack cpp

c++/prims_algorithm_MST.cpp
Hi **@rohithsprabhu** ,
Added **Prims Algo** to find **Minimum Spanning Tree**.
Please help to review and merge.
**Thanks.**
=> Added Prims Algorithm For Minimum Spanning Tree

c++/golomb_seq.cpp
Kindly accept this PR and add Hacktoberfest tag
=> Golomb Squence in C++

c++/hierholzer_algo.cpp
Kindly accept this PR and add Hacktoberfest tag
=> Hierholzer Algorithm

c++/boruvka_algo.cpp
Kindly accept this PR and add Hacktoberfest tag
=> Boruvka's Algorithm

c++/quickSort.cpp
Kindly accept this PR and add Hacktoberfest tag
=> Added Quick Sort

c++/fibonacciSearch.cpp
I have added Fibonacci Search in array in C++.
Please merge the PR and add hacktoberfest-accepted tag.
=> Fibonacci Search in array

c++/counting_sort.cpp
I have added Counting sort of an array in C++.
Please merge the PR and add hacktoberfest-accepted tag.
=> Counting sort of an array.

c++/burnTree.cpp
I have added Minimum time required to burn a tree from leaf node in C++.
Please merge the PR and add hacktoberfest-accepted tag.
=> Minimum time required to burn a tree from leaf node.

c++/bitonicElement.cpp
I have added to find bitonic element in bitonic sequence in C++.
Please merge PR and add hacktoberfest-accepted tag.
=> Bitonic Element in bitonic array

python/number_system_conversion.py
This is a simple Python program to convert binary, octal and hexadecimal numbers to decimal numbers
=> A program that performs number system conversion

c++/merge_sort.cpp
I have added the code of merge sort in c++. Please accept it @rohithsprabhu
=> Added code of merge sort in c++.

java/Palindrome.java
madam = Palindrome
madama = Not Palindrome
=> Added Palindrome using IF

c++/segment tree with lazy propagation.cpp
i have added "segment tree with lazy propagation algorithm"
please kindly accept this PR and added it to for hacktobarfest.
=> added segment tree with lazy propagation algorithm

c++/towerOfHanoi.cpp
Added the code and algorithm of Tower of Hanoi.
Request you to accept the pull request.
=> Added Tower of Hanoi code

c/MaxSumSubArray.c
Added a Max Sum Sub array code in c language
=> Added a Max Sum Sub array code in c language

python/Live Weather updates.py
Hi I have added my python program which gets live weather updates. Kindly review it and  accept the PR
=> Added Python File

c++/binarySearch.cpp
I have added C++ code for Binary Search. This will facilitate GitHub users to easily go through this repository.
I hope this will be a definitely a better contribution and you will merge my pull request.
Kindly add the **hacktoberfest-accepted** labels in this pull request while accepting.
Thanks a lot!
=> Added binary search c++ code

python/Rock Paper Scissors.py
Here's the file for hacktoberfest2022, since I accidentally sent it to hacktoberfest2021. Hope it doesn't arise any problems.
=> Rock Paper Scissors

c++/ShellSortingAlgo.cpp
Please have look on my cpp file.
=> Created and added my ShellSortingAlgo.cpp

java/MatrixChainMultiplicationImplementation.java
Please have look on my java file.
=> Created and Added my MatrixChainMultiplicationImplementation.java

c++/KadaneAlgorithm.cpp
Created Kadane ALgorithm to find Largest Sum Contiguous Subarray in cpp.
=> KadaneAlgorithm

c++/binary-search.cpp, python/menu-driven-binary-operations.py
Learn concept of binary search in C++
=> binary-search.cpp

c++/Singly_Linked_list_Implementation.cpp
=> Singly Linked List all operations

python/check-if-entered-year-is-a-leap-year.py
You will be able to check if the year you have entered is a leap year
=> check-if-entered-year-is-a-leap-year.py

c++/DoublyLinkedList.cpp
=> Doubly Linked List All Operations

python/insertion-sort.py
A code for insertion sort of array
=> insertion-sort.py

java/reversing a string
// java program to reverse a word
import java.io.*;
import java.util.Scanner;
class GFG {
public static void main (String[] args) {
String str= "Geeks", nstr="";
char ch;
System.out.print("Original word: ");
System.out.println("Geeks"); //Example word
for (int i=0; i<str.length(); i++)
{
ch= str.charAt(i); //extracts each character
nstr= ch+nstr; //adds each character in front of the existing string
}
System.out.println("Reversed word: "+ nstr);
}
}
=> Create reversing a string

c++/2N_NaturalNum_Rev.cpp
please merge/add my file to your repository with the label hacktoberfest. Happy Hacktoberfest-2022 bro 🎉
=> Number Reverse using Recursion

c#/TimeConverter.cs
=> Added TimeConverter

c++/printsubsequence.cpp
Printing subsequence using Recursion with proper naming .
please approve it with label hacktoberfest2022.
=> Printing subsequence || C++

c++/8-Queens-Problem.cpp
Our goal is to place 8 queens on a chess board such that no two queens attack each other. In the most naive solution, we would need to enumerate 64 choose 8 ~ 4B possibilities. A better naive solution is to realize that we can put each queen in a separate column, which leads to 8⁸~17M possibilities. We can do better by placing each queen in a separate column and a separate row that results in 8!~40K valid row permutations. In the implementation below, we assume that each queen occupies a different column, and we compute a valid row number for each of the 8 queens.
=> 8 Queens Problem using complete search

c/Bubble sort.c
=> bubble sort in c

c++/8-Queens-Problem.cpp, c++/FractionalKnapsackGreedyAlgo.cpp
A greedy knapsack problem consists of selecting what items to place in a knapsack of limited capacity W so as to maximize the total value of knapsack items, where each item has an associated weight and value. We can define a greedy heuristic to be a ratio of item value to item weight, i.e. we would like to greedily choose items that are simultaneously high value and low weight and sort the items based on this criteria. In the fractional knapsack problem, we are allowed to take fractions of an item (as opposed to 0–1 Knapsack).
=> Fractional Knapsack Greedy Algorithm
